### ISSUE TITLE
codebase

### ISSUE THREAD

**Issue by Ribster** [LonelyWolf/stm32#1]
Hey lonelywolf,

I'm making some STM32F030 examples where i used your code.
Because you are using the STM32F1, and i am using the STM32F0 the code is very different.
But i'm using the BMP180 registers and stuff. I know that's not your invention, because it's actually from bosch.
I just want to give you credit for your work, and i just don't know how to do it.
What can you agree upon as reference in my BMP180 code ?

Greetings,
Robbe

**Comment by LonelyWolf** [comment]
Of course, use the code as you want.

**Comment by Ribster** [comment]
https://github.com/Ribster/STM32-Projects/tree/master/stm32dev%20for%20STM32F030%20

I've put a reference in the readme.
Is that enough for you ?

**Comment by LonelyWolf** [comment]
Yep :)
