### ISSUE TITLE
What is the code license ?

### ISSUE THREAD

**Issue by marcelobarrosalmeida** [LonelyWolf/stm32#10]
Hello Dmitry,

I downloaded and modified your nRF24 library. A summary of changes is below and the code is attached. I would like to know your original license, as it is not specified in the project. 

If possible, I want to release it together my modifications using some BSD like license.

My modifications in the original code base are:

nrf24.c/.h

- support for ACK frames with user data payload 
- support for feature register
- some enumerations were transformed in types for later usage in my application
- support for interrupts (my default mode of operation)

nrf24_hal.c/.h

- support for the latest ST HAL API
- interrupt support

I created a nrf24_app.h/.c where user can choose between two communication scenarios:

1) unidirectional, PRX does not send anything but automatic ACK is enabled
2) bidirectional, where PRX sends a response using the ACK+PAYLOAD features

Users can choose between scenarios and set if they want to be PTX or PRX. Callbacks are provided for tx and rx operations (see main.c). It is easy to use.

[nrf24.zip](https://github.com/LonelyWolf/stm32/files/831975/nrf24.zip)

**Comment by LonelyWolf** [comment]
Hello.

I've already thought about to enclose some type of license (you not the first who asked about this), but unfortunately I have no much free time to dig in to all its features and nuances. Therefore, the text of the license may sound like this:
```
Basically, you can do whatever you want with the source: use, modify, sell, etc.
As long as I will not be held responsible.
```

In any case, I'll be happy if someone will find my code useful :)

**Comment by marcelobarrosalmeida** [comment]
Perfect, Dmity. I will cite your name/repository and adopt BSD Clause 3, together my modifications/extensions. If you like, I can clone your code and submit a pull request. I believe the "scenario" (nrf24_app.c) concept can help people starting with nRF24.
