### ISSUE TITLE
Small issue with the nrf24l01 example polling transmitter code

### ISSUE THREAD

**Issue by zigon15** [LonelyWolf/stm32#17]
![image](https://user-images.githubusercontent.com/16912854/63402291-f3802980-c419-11e9-8b5c-f52f600dbfb2.png)
I believe that should be `nRF24_CE_L();` not `nRF24_CE_H()` ?

**Comment by LonelyWolf** [comment]
Yes, you are right. Thanks for the remark.

PS: spent a long time searching this in the code; then suddenly realized that it is the documentation... :trollface:
