### ISSUE TITLE
The usb-mic project hard fault

### ISSUE THREAD

**Issue by MynaBay** [LonelyWolf/stm32#27]
I'm trying to run the usb-mic project on a Nucleo-L4R5Zi board. I created an empty project for this board in STM32CubeIDE and drag/dropped the files into the project. It builds OK but I hit a hard fault in system init on the line:
    RCC->CR |= (uint32_t)0x00000100;

I suspect the problem is with how I'm building it. Are there instructions on building this, or an updated project for the STM32CubeIDE?

Any guidance is greatly appreciated.

**Comment by LonelyWolf** [comment]
The usb_mic project will work only on L1 MCUs.
If you were seduced by the phrase "Will work on all STM32L family with hardware USB" from the README.MD, sorry for that...
That was written a long long ago, then there was no L4 series yet.
