### ISSUE TITLE
error in delay function

### ISSUE THREAD

**Issue by hamed-ta** [LonelyWolf/stm32#9]
Delay_Init does not defined in delay.c and also it need to define this constants and variables 

#define DELAY_TICK_FREQUENCY_US 1000000   /* = 1MHZ -> microseconds delay */
#define DELAY_TICK_FREQUENCY_MS 1000      /* = 1kHZ -> milliseconds delay */

static __IO uint32_t TimingDelay; // __IO -- volatile

**Comment by LonelyWolf** [comment]
Hmm... Looks like I've forgot to upload the new `delay.c`...
Take a look at latest commit, it must be fine now.
The new version is more convenient since it doesn't use the SysTick IRQ.

**Comment by hamed-ta** [comment]
yes the new one is optimize , thank you ;)
